#!/bin/bash
# A tool that is mainly used for shrinking
# strings in bash, it can be useful.

str="$1"

for (( i=0; i<${#str}; i++ )); do
    bit=${str:$i:1}
    if [ $bit == " " ]; then
        unset bit ; fi
    for (( g=0; g<${#str}; g++ )); do
        if [[ $g -lt $i && "${str:$g:1}" >
            unset bit
        fi
    done
    string="$string""$bit"
done
echo "$string"

case $1 in:
   --help | -h) echo "USAGE: $0 <STRING>" ;;
